Fix scripts

diff --git a/initialization/check-terraform b/initialization/check-terraform
--- a/initialization/check-terraform
+++ b/initialization/check-terraform
@@ -5,4 +5,9 @@ if [ ! -d "$HOME/.terraform.d" ]; then
   exit 1
 fi
 
+if [ ! -d "$HOME/.terraform/plugins/linux_amd64" ]; then
+  fail-message "Terraform has not been initialized properly, plugins not found"
+  exit 1
+fi
+
 exit 0
